// Package reset проходит по всем файлам в проекте и добавляет метод Reset()
// Метод добавляется структурам, аннотированным // generate:reset
package reset

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"go/types"
	"os"
	"path"
	"path/filepath"
	"slices"
	"strconv"
	"strings"
	"text/template"

	"golang.org/x/tools/go/packages"
)

type targetSpec struct {
	file *ast.File
	ts   *ast.TypeSpec
}

type methodData struct {
	TypeName string
	Body     string // accumulated by genReset, unindented lines
}

type importSpec struct {
	Alias string
	Path  string
}

type fileData struct {
	Package string
	Imports []importSpec
	Methods []methodData
}

const tmplSrc = `// Code generated by github.com/LifeforDream/gometrics/cmd/reset; DO NOT EDIT.
package {{.Package}}
{{if .Imports}}
import (
{{range .Imports}}{{if .Alias}}       {{.Alias}} {{printf "%q" .Path}}
{{else}}      {{printf "%q" .Path}}
{{end}}{{end}})
{{end}}
{{range .Methods}}
func (rs *{{.TypeName}}) Reset() {
    if rs == nil {
        return
    }
{{.Body}}
}
{{end}}
`

const resetFilename = "reset.gen.go"

// Run запускает генерацию кода
func Run(root string) error {
	pkgs, err := loadPackages(root)
	if err != nil {
		return err
	}
	for _, pkg := range pkgs {
		var targets []targetSpec
		for _, file := range pkg.Syntax {
			filename := pkg.Fset.Position(file.Pos()).Filename
			if filepath.Base(filename) == resetFilename {
				continue
			}
			targets = append(targets, resetTargets(file)...)
		}
		if len(targets) == 0 {
			continue
		}

		data, err := generate(pkg, targets)
		if err != nil {
			return fmt.Errorf("generating reset methods for package %s: %w", pkg.PkgPath, err)
		}

		resetFp := filepath.Join(pkg.Dir, resetFilename)
		if err := os.WriteFile(resetFp, data, 0o644); err != nil {
			return fmt.Errorf("writing %s: %w", resetFp, err)
		}
	}
	return nil
}

// resetTargets возвращает []struct{*ast.File, *ast.TypeSpec} для каждой структуры в файле file
// с директивой // generate:reset.
func resetTargets(file *ast.File) []targetSpec {
	var targets []targetSpec
	for _, decl := range file.Decls {
		gd, ok := decl.(*ast.GenDecl)
		if !ok || gd.Tok != token.TYPE {
			continue
		}
		for _, spec := range gd.Specs {
			ts := spec.(*ast.TypeSpec)
			if _, ok := ts.Type.(*ast.StructType); !ok {
				continue
			}
			if hasResetDirective(gd, ts, len(gd.Specs)) {
				targets = append(targets, targetSpec{file: file, ts: ts})
			}
		}
	}
	return targets
}

func loadPackages(root string) ([]*packages.Package, error) {
	cfg := &packages.Config{
		Mode: packages.NeedName | packages.NeedFiles | packages.NeedSyntax | packages.NeedTypes | packages.NeedTypesInfo,
		Dir:  root,
	}
	pkgs, err := packages.Load(cfg, "./...")
	if err != nil {
		return nil, err
	}
	for _, pkg := range pkgs {
		for _, e := range pkg.Errors {
			return nil, e
		}
	}
	return pkgs, nil
}

func hasResetDirective(gd *ast.GenDecl, ts *ast.TypeSpec, specCount int) bool {
	doc := ts.Doc
	if doc == nil && specCount == 1 {
		doc = gd.Doc
	}
	if doc == nil {
		return false
	}
	for _, c := range doc.List {
		if strings.TrimSpace(strings.TrimPrefix(c.Text, "//")) == "generate:reset" {
			return true
		}
	}
	return false
}

// generate строит исходный текст reset.gen.go для пакета pkg: для каждого
// target генерирует метод Reset() (через genReset, по полям структуры),
// затем отдаёт на генерацию в tmplSrc. Ошибка от genReset (например,
// конфликт алиасов импорта) прерывает генерацию и пробрасывается наверх.
func generate(pkg *packages.Package, targets []targetSpec) ([]byte, error) {
	fd := fileData{
		Package: pkg.Name,
		Imports: make([]importSpec, 0),
		Methods: make([]methodData, 0),
	}
	imports := make(map[string]string)

	for _, target := range targets {
		st, ok := target.ts.Type.(*ast.StructType)
		if !ok {
			continue
		}

		var body strings.Builder
		for _, field := range st.Fields.List {
			for _, ident := range field.Names {
				if ident.Name == "_" {
					continue
				}
				err := genReset(&body, "rs."+ident.Name, field.Type, imports, target, pkg.TypesInfo, false)
				if err != nil {
					return nil, err
				}
			}
		}
		fd.Methods = append(fd.Methods, methodData{
			TypeName: target.ts.Name.Name,
			Body:     body.String(),
		})
	}

	if len(imports) > 0 {
		importPaths := make([]string, 0)

		for importPath := range imports {
			importPaths = append(importPaths, importPath)
		}
		slices.Sort(importPaths)
		for _, path := range importPaths {
			if alias := imports[path]; alias != "" {
				fd.Imports = append(fd.Imports, importSpec{Alias: alias, Path: path})
			} else {
				fd.Imports = append(fd.Imports, importSpec{Path: path})
			}
		}
	}

	var resetTmpl = template.Must(template.New("reset").Parse(tmplSrc))
	var buf bytes.Buffer

	err := resetTmpl.Execute(&buf, fd)
	if err != nil {
		return nil, fmt.Errorf("error populating template: %w", err)
	}

	src, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, err
	}
	return src, nil
}

// genReset пишет код сброса значения lvalue (например, "rs.x" или "*rs.x")
// в соответствии с его типом typ.
//
// skipDelegation подавляет делегирование в Reset() на этом уровне рекурсии
// для веток *ast.Ident и *ast.SelectorExpr. Он нужен только для рекурсивного
// вызова из generateStar: там lvalue уже имеет вид "*x", и если бы тип всё
// же делегировал в Reset(), получилось бы "*x.Reset()" — из-за приоритета
// операторов это разбирается как "*(x.Reset())", то есть попытка
// разыменовать результат вызова без возвращаемого значения (ошибка
// компиляции), а вовсе не то же самое, что "x.Reset()". Эта ветка внутри
// generateStar физически недостижима в рантайме, если у типа есть Reset()
// (рантайм-проверка interface{ Reset() } к этому моменту уже была бы true),
// но код всё равно должен компилироваться, поэтому здесь всегда используется
// обычное обнуление, как до появления делегирования в Reset().
func genReset(sb *strings.Builder, lvalue string, typ ast.Expr, imports map[string]string, target targetSpec, info *types.Info, skipDelegation bool) error {
	switch t := typ.(type) {
	// примитивы
	case *ast.Ident:
		if !skipDelegation && hasResetMethod(info.TypeOf(typ)) {
			// значимый (не по указателю) тип с собственным Reset() — делегируем ему,
			// а не обнуляем поле целиком через *new(T).
			fmt.Fprintf(sb, "%s.Reset()\n", lvalue)
		} else {
			switch info.TypeOf(typ).Underlying().(type) {
			case *types.Slice:
				fmt.Fprintf(sb, "%s\n", generateSlice(lvalue))
			case *types.Map:
				fmt.Fprintf(sb, "%s\n", generateMap(lvalue))
			default:
				fmt.Fprintf(sb, "%s\n", generatePrimitive(lvalue, typ))
			}
		}
	// указатели
	case *ast.StarExpr:
		code, err := generateStar(lvalue, t.X, imports, target, info)
		if err != nil {
			return fmt.Errorf("error while generating star expression %w", err)
		}
		fmt.Fprintf(sb, "%s\n", code)
	// слайсы и массивы
	case *ast.ArrayType:
		if t.Len != nil {
			fmt.Fprintf(sb, "%s\n", generatePrimitive(lvalue, typ)) // just recreate an array
		} else {
			fmt.Fprintf(sb, "%s\n", generateSlice(lvalue)) // truncate slice
		}
	// мапы
	case *ast.MapType:
		fmt.Fprintf(sb, "%s\n", generateMap(lvalue))
	// примитивы из импортируемых пакетов
	case *ast.SelectorExpr:
		// значимый тип из другого пакета со своим Reset() — делегируем ему,
		// как и для локальных типов в ветке *ast.Ident. Это не требует
		// упоминания пакета в сгенерированном коде (просто "rs.field.Reset()"),
		// поэтому импорт резолвить и регистрировать не нужно.
		if !skipDelegation && hasResetMethod(info.TypeOf(typ)) {
			fmt.Fprintf(sb, "%s.Reset()\n", lvalue)
			return nil
		}
		// иначе полю понадобится квалифицированное имя типа для *new(pkg.T) —
		// резолвим и регистрируем импорт.
		pident, ok := t.X.(*ast.Ident)
		if !ok {
			return nil
		}
		ipath, alias, ok := requiredImport(target.file, pident.Name)
		if !ok {
			return nil
		}
		exalias, exist := imports[ipath]
		if exist && exalias != alias {
			return fmt.Errorf("multiple aliased import statements for one package: %s (%s, %s)", ipath, exalias, alias)
		}
		if alias != "" {
			imports[ipath] = alias
		} else {
			imports[ipath] = ""
		}
		fmt.Fprintf(sb, "%s\n", generatePrimitive(lvalue, typ))
	}
	return nil
}

// hasResetMethod проверяет, что *t (или сам t) реализует метод Reset() без
// параметров и результатов. Используется только для значимых (не по
// указателю) полей: для них lvalue всё равно адресуемо (доступ идёт через
// указатель-получатель rs), поэтому метод с указательным получателем тоже
// найдётся через метод-сет *t.
func hasResetMethod(t types.Type) bool {
	sel := types.NewMethodSet(types.NewPointer(t)).Lookup(nil, "Reset")
	if sel == nil {
		return false
	}
	sig, ok := sel.Obj().Type().(*types.Signature)
	return ok && sig.Params().Len() == 0 && sig.Results().Len() == 0
}

func generatePrimitive(name string, exp ast.Expr) string {
	typeName := types.ExprString(exp)
	return fmt.Sprintf("%s = *new(%s)", name, typeName)
}

func generateSlice(name string) string {
	return fmt.Sprintf("%s = %s[:0]", name, name)
}

func generateMap(name string) string {
	return fmt.Sprintf("clear(%s)", name)
}

// generateStar генерирует методы для указателей
//
// указатель может быть как на примитив - и тогда нужно рекурсивно выбрать правильный метод
// так и на дочернюю структуру с методом Reset() - и тогда этот метод нужно вызвать.
func generateStar(name string, e ast.Expr, imports map[string]string, target targetSpec, info *types.Info) (string, error) {
	var sb strings.Builder
	fmt.Fprintf(&sb, "if %s != nil {\n", name)
	fmt.Fprintf(&sb, "if resetter, ok := any(%s).(interface{ Reset() }); ok {\n", name)
	fmt.Fprintf(&sb, "resetter.Reset()\n} else {\n")
	err := genReset(&sb, "*"+name, e, imports, target, info, true) // рекурсия тут; skipDelegation=true, см. doc genReset
	if err != nil {
		return "", fmt.Errorf("error while generating nested expression inside star %w", err)
	}
	fmt.Fprintf(&sb, "}\n}\n")
	return sb.String(), nil
}

// requiredImport ищет в объявлениях импорта file тот, что вводит в область
// видимости идентификатор пакета pkgIdent (взятый из X селектора вида
// pkgIdent.Type), и возвращает его путь импорта и алиас. Если у импорта есть
// явный алиас, сравнение идёт по нему; иначе — по базовому имени пути
// импорта (path.Base), что соответствует реальному имени пакета для
// большинства путей вида ".../pkgname". ok == false, если подходящий импорт
// не найден.
func requiredImport(file *ast.File, pkgIdent string) (ipath string, alias string, ok bool) {
	for _, imp := range file.Imports {
		importPath, _ := strconv.Unquote(imp.Path.Value)
		switch {
		case imp.Name != nil && imp.Name.Name == pkgIdent:
			return importPath, imp.Name.Name, true // mrand "math/rand"
		case imp.Name == nil && path.Base(importPath) == pkgIdent:
			return importPath, "", true // "time" → time
		}
	}
	return "", "", false
}
